spring:
  application:
    name: ms-books-catalogue

  elasticsearch: # se agrega Configuración de ElasticSearch
    uris: https://21c0ffd9506f4877a09241cd24f630e0.us-central1.gcp.cloud.es.io:9243
    username: ms-books-catalogue
    password: DesarrolloUnir01@

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  packages-to-scan: com.unir.ms_books_catalogue.controller
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
  show-actuator: true
  scan-packages: com.unir.ms_books_catalogue